name: Pylint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install Pylint
      run: |
        python -m pip install --upgrade pip
        pip install tox==4.11.3
    - name: Analysing the code with pylint
      run: |
        tox -e pylint -- src
        tox -e pylint -- tests

